project:
  type: website
  output-dir: docs

website:
  title: "QMII & QFT Notes"
  site-url: "https://zty624.github.io/qm2qft"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "QM II"
        href: qm2/index.qmd
      - text: "QFT"
        href: qft/index.qmd
      - text: "About"
        href: about.qmd
  
  sidebar: 
    - id: qm2
      style: docked
      pinned: true
      search: true
      contents:
        - text: "Index"
          href: qm2/index.qmd
        - text: "Chap 1: Basic Concepts"
          href: qm2/chap1.qmd
        - text: "Chap 2: Dynamics and Geometric Phases"
          href: qm2/chap2.qmd
    
    - id: qft
      style: docked
      pinned: true
      search: true
      contents:
        - text: "Index"
          href: qft/index.qmd
        - text: "TBD"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3